# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Chippewa spellchecker"
ciw = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Chippewa, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
ciw = "TRANSLATE: A spellchecker for Chippewa, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.ciw"

[windows]
system_product_code = "{263FA97A-B138-4309-9D53-ED7F9CF8DC43}_is1"
legacy_product_codes = [
    { value = "18419869-19CA-4AAC-8A92-D13C8CE25ECE", kind = "nsis" },
    { value = "E91166AC-169E-4AAE-B648-3F37E99ED539", kind = "nsis" }
]

[package.speller]
name = "Chippewa"
version = "0.1.1"

[package.grammar]
name = "Chippewa"
version = "0.1.0"

[package.tts-text-proc]
name = "Chippewa"
version = "0.1.0"

[package.hyphenator]
name = "__UNDEFINED__"
version = "0.1.0"
