template = "https://github.com/giellalt/template-lang-und"
rev_id = 264
template_sha = "120f384c016282eb1fbbcc762e0ac6064a37eb45"

[replacements]
__GLOTTOLOG_ID__ = "chip1241"
__REPO__ = "lang-ciw"
__UND2C__ = "ciw"
__UNDEFINED__ = "Chippewa"
__UND__ = "ciw"
